theme: jekyll-theme-minimal
title: "Xing Yu Yi"
tagline: "Maths and all sorts"
description: "Welcome to my site!"

author:
  name: "Xing Yu Yi"
  email: "xyy22@cam.ac.uk"
  social:
    github: "xyy258"

plugins:
  - jekyll-remote-theme
remote_theme: qwtel/hydejack
