title: "Xing Yu Yi"
tagline: "Maths and all sorts"
description: "Welcome to my site!"

# Domain settings
url: "https://xyy258.github.io"
baseurl: ""

# Author profile
author:
  name: "Xing Yu Yi"
  picture: "/assets/img/profile.jpg"
  email: "xyy22@cam.ac.uk"
  social:
    github: "xyy258"

# Theme setup
theme: jekyll-theme-hydejack

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-gist
